/*
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractVideoGenValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.mlh.videoGen.VideoGenPackage.eINSTANCE);
		return result;
	}
}
