/*
 * generated by Xtext 2.15.0
 */
package fr.istic.ide

import com.google.inject.Guice
import fr.istic.VideoGenRuntimeModule
import fr.istic.VideoGenStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class VideoGenIdeSetup extends VideoGenStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new VideoGenRuntimeModule, new VideoGenIdeModule))
	}
	
}
