/**
 * generated by Xtext 2.15.0
 */
package fr.istic;

import fr.istic.VideoGenStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class VideoGenStandaloneSetup extends VideoGenStandaloneSetupGenerated {
  public static void doSetup() {
    new VideoGenStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
