/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Display stats</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mlh.videoGen.Display_stats#getDisplay_stats <em>Display stats</em>}</li>
 * </ul>
 *
 * @see org.xtext.mlh.videoGen.VideoGenPackage#getDisplay_stats()
 * @model
 * @generated
 */
public interface Display_stats extends EObject
{
  /**
   * Returns the value of the '<em><b>Display stats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Display stats</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Display stats</em>' attribute.
   * @see #setDisplay_stats(int)
   * @see org.xtext.mlh.videoGen.VideoGenPackage#getDisplay_stats_Display_stats()
   * @model
   * @generated
   */
  int getDisplay_stats();

  /**
   * Sets the value of the '{@link org.xtext.mlh.videoGen.Display_stats#getDisplay_stats <em>Display stats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Display stats</em>' attribute.
   * @see #getDisplay_stats()
   * @generated
   */
  void setDisplay_stats(int value);

} // Display_stats
