/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Video Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mlh.videoGen.VideoGenPackage#getVideoType()
 * @model
 * @generated
 */
public interface VideoType extends EObject
{
} // VideoType
