/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mlh.videoGen.VideoGenFactory
 * @model kind="package"
 * @generated
 */
public interface VideoGenPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "videoGen";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mlh/VideoGen";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "videoGen";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoGenPackage eINSTANCE = org.xtext.mlh.videoGen.impl.VideoGenPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.VideoGenImpl <em>Video Gen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.VideoGenImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoGen()
   * @generated
   */
  int VIDEO_GEN = 0;

  /**
   * The feature id for the '<em><b>Videos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN__VIDEOS = 0;

  /**
   * The number of structural features of the '<em>Video Gen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.VideoTypeImpl <em>Video Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.VideoTypeImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoType()
   * @generated
   */
  int VIDEO_TYPE = 1;

  /**
   * The number of structural features of the '<em>Video Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.MandatoryImpl <em>Mandatory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.MandatoryImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getMandatory()
   * @generated
   */
  int MANDATORY = 2;

  /**
   * The feature id for the '<em><b>Videoseq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANDATORY__VIDEOSEQ = VIDEO_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mandatory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANDATORY_FEATURE_COUNT = VIDEO_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.OptionalImpl <em>Optional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.OptionalImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getOptional()
   * @generated
   */
  int OPTIONAL = 3;

  /**
   * The feature id for the '<em><b>Videoseq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL__VIDEOSEQ = VIDEO_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Optional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_FEATURE_COUNT = VIDEO_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.AlternativesImpl <em>Alternatives</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.AlternativesImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getAlternatives()
   * @generated
   */
  int ALTERNATIVES = 4;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES__ID = VIDEO_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Videoseqs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES__VIDEOSEQS = VIDEO_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Alternatives</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES_FEATURE_COUNT = VIDEO_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl <em>Video Seq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.VideoSeqImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoSeq()
   * @generated
   */
  int VIDEO_SEQ = 5;

  /**
   * The feature id for the '<em><b>Vid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ__VID = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ__URL = 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ__DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ__DURATION = 3;

  /**
   * The feature id for the '<em><b>Display stats</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ__DISPLAY_STATS = 4;

  /**
   * The number of structural features of the '<em>Video Seq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_SEQ_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.DescriptionImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__DESCRIPTION = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.DurationImpl <em>Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.DurationImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDuration()
   * @generated
   */
  int DURATION = 7;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__DURATION = 0;

  /**
   * The number of structural features of the '<em>Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mlh.videoGen.impl.Display_statsImpl <em>Display stats</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mlh.videoGen.impl.Display_statsImpl
   * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDisplay_stats()
   * @generated
   */
  int DISPLAY_STATS = 8;

  /**
   * The feature id for the '<em><b>Display stats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISPLAY_STATS__DISPLAY_STATS = 0;

  /**
   * The number of structural features of the '<em>Display stats</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISPLAY_STATS_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.VideoGen <em>Video Gen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Gen</em>'.
   * @see org.xtext.mlh.videoGen.VideoGen
   * @generated
   */
  EClass getVideoGen();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mlh.videoGen.VideoGen#getVideos <em>Videos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Videos</em>'.
   * @see org.xtext.mlh.videoGen.VideoGen#getVideos()
   * @see #getVideoGen()
   * @generated
   */
  EReference getVideoGen_Videos();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.VideoType <em>Video Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Type</em>'.
   * @see org.xtext.mlh.videoGen.VideoType
   * @generated
   */
  EClass getVideoType();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Mandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mandatory</em>'.
   * @see org.xtext.mlh.videoGen.Mandatory
   * @generated
   */
  EClass getMandatory();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mlh.videoGen.Mandatory#getVideoseq <em>Videoseq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Videoseq</em>'.
   * @see org.xtext.mlh.videoGen.Mandatory#getVideoseq()
   * @see #getMandatory()
   * @generated
   */
  EReference getMandatory_Videoseq();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Optional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Optional</em>'.
   * @see org.xtext.mlh.videoGen.Optional
   * @generated
   */
  EClass getOptional();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mlh.videoGen.Optional#getVideoseq <em>Videoseq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Videoseq</em>'.
   * @see org.xtext.mlh.videoGen.Optional#getVideoseq()
   * @see #getOptional()
   * @generated
   */
  EReference getOptional_Videoseq();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Alternatives <em>Alternatives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alternatives</em>'.
   * @see org.xtext.mlh.videoGen.Alternatives
   * @generated
   */
  EClass getAlternatives();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.Alternatives#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.mlh.videoGen.Alternatives#getId()
   * @see #getAlternatives()
   * @generated
   */
  EAttribute getAlternatives_Id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mlh.videoGen.Alternatives#getVideoseqs <em>Videoseqs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Videoseqs</em>'.
   * @see org.xtext.mlh.videoGen.Alternatives#getVideoseqs()
   * @see #getAlternatives()
   * @generated
   */
  EReference getAlternatives_Videoseqs();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.VideoSeq <em>Video Seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Seq</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq
   * @generated
   */
  EClass getVideoSeq();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.VideoSeq#getVid <em>Vid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vid</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq#getVid()
   * @see #getVideoSeq()
   * @generated
   */
  EAttribute getVideoSeq_Vid();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.VideoSeq#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq#getUrl()
   * @see #getVideoSeq()
   * @generated
   */
  EAttribute getVideoSeq_Url();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mlh.videoGen.VideoSeq#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq#getDescription()
   * @see #getVideoSeq()
   * @generated
   */
  EReference getVideoSeq_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mlh.videoGen.VideoSeq#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq#getDuration()
   * @see #getVideoSeq()
   * @generated
   */
  EReference getVideoSeq_Duration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mlh.videoGen.VideoSeq#getDisplay_stats <em>Display stats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Display stats</em>'.
   * @see org.xtext.mlh.videoGen.VideoSeq#getDisplay_stats()
   * @see #getVideoSeq()
   * @generated
   */
  EReference getVideoSeq_Display_stats();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see org.xtext.mlh.videoGen.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.Description#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.mlh.videoGen.Description#getDescription()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Duration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Duration</em>'.
   * @see org.xtext.mlh.videoGen.Duration
   * @generated
   */
  EClass getDuration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.Duration#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.mlh.videoGen.Duration#getDuration()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Duration();

  /**
   * Returns the meta object for class '{@link org.xtext.mlh.videoGen.Display_stats <em>Display stats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Display stats</em>'.
   * @see org.xtext.mlh.videoGen.Display_stats
   * @generated
   */
  EClass getDisplay_stats();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mlh.videoGen.Display_stats#getDisplay_stats <em>Display stats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Display stats</em>'.
   * @see org.xtext.mlh.videoGen.Display_stats#getDisplay_stats()
   * @see #getDisplay_stats()
   * @generated
   */
  EAttribute getDisplay_stats_Display_stats();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VideoGenFactory getVideoGenFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.VideoGenImpl <em>Video Gen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.VideoGenImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoGen()
     * @generated
     */
    EClass VIDEO_GEN = eINSTANCE.getVideoGen();

    /**
     * The meta object literal for the '<em><b>Videos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_GEN__VIDEOS = eINSTANCE.getVideoGen_Videos();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.VideoTypeImpl <em>Video Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.VideoTypeImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoType()
     * @generated
     */
    EClass VIDEO_TYPE = eINSTANCE.getVideoType();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.MandatoryImpl <em>Mandatory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.MandatoryImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getMandatory()
     * @generated
     */
    EClass MANDATORY = eINSTANCE.getMandatory();

    /**
     * The meta object literal for the '<em><b>Videoseq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANDATORY__VIDEOSEQ = eINSTANCE.getMandatory_Videoseq();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.OptionalImpl <em>Optional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.OptionalImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getOptional()
     * @generated
     */
    EClass OPTIONAL = eINSTANCE.getOptional();

    /**
     * The meta object literal for the '<em><b>Videoseq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTIONAL__VIDEOSEQ = eINSTANCE.getOptional_Videoseq();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.AlternativesImpl <em>Alternatives</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.AlternativesImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getAlternatives()
     * @generated
     */
    EClass ALTERNATIVES = eINSTANCE.getAlternatives();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALTERNATIVES__ID = eINSTANCE.getAlternatives_Id();

    /**
     * The meta object literal for the '<em><b>Videoseqs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALTERNATIVES__VIDEOSEQS = eINSTANCE.getAlternatives_Videoseqs();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl <em>Video Seq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.VideoSeqImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getVideoSeq()
     * @generated
     */
    EClass VIDEO_SEQ = eINSTANCE.getVideoSeq();

    /**
     * The meta object literal for the '<em><b>Vid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_SEQ__VID = eINSTANCE.getVideoSeq_Vid();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_SEQ__URL = eINSTANCE.getVideoSeq_Url();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_SEQ__DESCRIPTION = eINSTANCE.getVideoSeq_Description();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_SEQ__DURATION = eINSTANCE.getVideoSeq_Duration();

    /**
     * The meta object literal for the '<em><b>Display stats</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_SEQ__DISPLAY_STATS = eINSTANCE.getVideoSeq_Display_stats();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.DescriptionImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__DESCRIPTION = eINSTANCE.getDescription_Description();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.DurationImpl <em>Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.DurationImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDuration()
     * @generated
     */
    EClass DURATION = eINSTANCE.getDuration();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__DURATION = eINSTANCE.getDuration_Duration();

    /**
     * The meta object literal for the '{@link org.xtext.mlh.videoGen.impl.Display_statsImpl <em>Display stats</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mlh.videoGen.impl.Display_statsImpl
     * @see org.xtext.mlh.videoGen.impl.VideoGenPackageImpl#getDisplay_stats()
     * @generated
     */
    EClass DISPLAY_STATS = eINSTANCE.getDisplay_stats();

    /**
     * The meta object literal for the '<em><b>Display stats</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISPLAY_STATS__DISPLAY_STATS = eINSTANCE.getDisplay_stats_Display_stats();

  }

} //VideoGenPackage
