/**
 * generated by Xtext 2.15.0
 */
package fr.istic.videoGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Black White Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.videoGen.VideoGenPackage#getBlackWhiteFilter()
 * @model
 * @generated
 */
public interface BlackWhiteFilter extends Filter
{
} // BlackWhiteFilter
