/**
 * generated by Xtext 2.15.0
 */
package fr.istic.videoGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.videoGen.VideoGenPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends EObject
{
} // Filter
