/**
 * generated by Xtext 2.15.0
 */
package fr.istic.videoGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Image Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.videoGen.ImageDescription#getImageid <em>Imageid</em>}</li>
 *   <li>{@link fr.istic.videoGen.ImageDescription#getTop <em>Top</em>}</li>
 *   <li>{@link fr.istic.videoGen.ImageDescription#getBottom <em>Bottom</em>}</li>
 * </ul>
 *
 * @see fr.istic.videoGen.VideoGenPackage#getImageDescription()
 * @model
 * @generated
 */
public interface ImageDescription extends MediaDescription
{
  /**
   * Returns the value of the '<em><b>Imageid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imageid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imageid</em>' attribute.
   * @see #setImageid(String)
   * @see fr.istic.videoGen.VideoGenPackage#getImageDescription_Imageid()
   * @model
   * @generated
   */
  String getImageid();

  /**
   * Sets the value of the '{@link fr.istic.videoGen.ImageDescription#getImageid <em>Imageid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imageid</em>' attribute.
   * @see #getImageid()
   * @generated
   */
  void setImageid(String value);

  /**
   * Returns the value of the '<em><b>Top</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Top</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Top</em>' attribute.
   * @see #setTop(String)
   * @see fr.istic.videoGen.VideoGenPackage#getImageDescription_Top()
   * @model
   * @generated
   */
  String getTop();

  /**
   * Sets the value of the '{@link fr.istic.videoGen.ImageDescription#getTop <em>Top</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Top</em>' attribute.
   * @see #getTop()
   * @generated
   */
  void setTop(String value);

  /**
   * Returns the value of the '<em><b>Bottom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bottom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bottom</em>' attribute.
   * @see #setBottom(String)
   * @see fr.istic.videoGen.VideoGenPackage#getImageDescription_Bottom()
   * @model
   * @generated
   */
  String getBottom();

  /**
   * Sets the value of the '{@link fr.istic.videoGen.ImageDescription#getBottom <em>Bottom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bottom</em>' attribute.
   * @see #getBottom()
   * @generated
   */
  void setBottom(String value);

} // ImageDescription
