/**
 * generated by Xtext 2.15.0
 */
package fr.istic.videoGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Video Generator Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.videoGen.VideoGeneratorModel#getInformation <em>Information</em>}</li>
 *   <li>{@link fr.istic.videoGen.VideoGeneratorModel#getMedias <em>Medias</em>}</li>
 * </ul>
 *
 * @see fr.istic.videoGen.VideoGenPackage#getVideoGeneratorModel()
 * @model
 * @generated
 */
public interface VideoGeneratorModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Information</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Information</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Information</em>' containment reference.
   * @see #setInformation(VideoGenInformation)
   * @see fr.istic.videoGen.VideoGenPackage#getVideoGeneratorModel_Information()
   * @model containment="true"
   * @generated
   */
  VideoGenInformation getInformation();

  /**
   * Sets the value of the '{@link fr.istic.videoGen.VideoGeneratorModel#getInformation <em>Information</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Information</em>' containment reference.
   * @see #getInformation()
   * @generated
   */
  void setInformation(VideoGenInformation value);

  /**
   * Returns the value of the '<em><b>Medias</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.videoGen.Media}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medias</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medias</em>' containment reference list.
   * @see fr.istic.videoGen.VideoGenPackage#getVideoGeneratorModel_Medias()
   * @model containment="true"
   * @generated
   */
  EList<Media> getMedias();

} // VideoGeneratorModel
