/*
 * generated by Xtext 2.15.0
 */
package fr.istic.ui;

import com.google.inject.Injector;
import fr.istic.videogen.ui.internal.VideogenActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(VideogenActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		VideogenActivator activator = VideogenActivator.getInstance();
		return activator != null ? activator.getInjector(VideogenActivator.FR_ISTIC_VIDEOGEN) : null;
	}

}
