/**
 * generated by Xtext 2.15.0
 */
package fr.istic.ui.contentassist;

import fr.istic.ui.contentassist.AbstractVideoGenProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class VideoGenProposalProvider extends AbstractVideoGenProposalProvider {
}
