/**
 * generated by Xtext 2.15.0
 */
package fr.istic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.istic.VideoGenRuntimeModule;
import fr.istic.VideoGenStandaloneSetup;
import fr.istic.ide.VideoGenIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class VideoGenIdeSetup extends VideoGenStandaloneSetup {
  @Override
  public Injector createInjector() {
    VideoGenRuntimeModule _videoGenRuntimeModule = new VideoGenRuntimeModule();
    VideoGenIdeModule _videoGenIdeModule = new VideoGenIdeModule();
    return Guice.createInjector(Modules2.mixin(_videoGenRuntimeModule, _videoGenIdeModule));
  }
}
