/**
 * generated by Xtext 2.15.0
 */
package fr.istic.ide;

import fr.istic.ide.AbstractVideoGenIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class VideoGenIdeModule extends AbstractVideoGenIdeModule {
}
