@startuml

class Activity {
    -name: String
    -cost: Float
}
enum ActivityType {
    SAILING
}
abstract class BaseEntity {
    -id: Long
    -createdAt: Instant
    -updatedAt: Instant
}
class City {
    -name: String
    -postalCode: Integer
    -longitude: Float
}
class Department {
    -name: String
    -code: int
}
class Person {
    -firstName: String
    -lastName: String
}
class Region {
    -name: String
}

BaseEntity <|-- Activity
BaseEntity <|-- City
BaseEntity <|-- Department
BaseEntity <|-- Person
BaseEntity <|-- Region
Activity --> "*" City
Activity --> "1" ActivityType
Person --> "1" City
Person --> "*" City
Person --> "*" Department
Person --> "*" Region
Department "1" <-- City
Region "1" -- "*" Department
Person --> "*" Activity
@enduml