/*
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVideoGenScopeProvider extends DelegatingScopeProvider {
}
