@startuml
box "Future"
    participant "f : ValueFuture" as f
end box
box "Servant"
    participant "d: Diffusion" as d
    participant "g: Generator" as g
end box
box "Method Invocation"
    participant "mi : MethodInvoc" as mi
end box
box "Active Object"
    participant "aq : ActiveQueue" as aq
end box
box "Scheduler"
    participant "s : Scheduler" as s
end box
activate g
activate s
s -> aq: get()
activate aq
aq --> s: mi
deactivate aq
s -> mi: call()
activate mi
mi -> g: getValue(m)
deactivate mi
g -> d: getValue(m)
deactivate g
activate d
d -> f: setValue(v)
deactivate d
activate f
f --> d
deactivate f
activate d
d --> g
deactivate d
activate g
g --> mi
activate mi
mi --> s
deactivate mi
s -> f: setDone()
activate f
deactivate f
@enduml