/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.mlh.videoGen.Display_stats;
import org.xtext.mlh.videoGen.VideoGenPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Display stats</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mlh.videoGen.impl.Display_statsImpl#getDisplay_stats <em>Display stats</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Display_statsImpl extends MinimalEObjectImpl.Container implements Display_stats
{
  /**
   * The default value of the '{@link #getDisplay_stats() <em>Display stats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplay_stats()
   * @generated
   * @ordered
   */
  protected static final int DISPLAY_STATS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDisplay_stats() <em>Display stats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplay_stats()
   * @generated
   * @ordered
   */
  protected int display_stats = DISPLAY_STATS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Display_statsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoGenPackage.Literals.DISPLAY_STATS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getDisplay_stats()
  {
    return display_stats;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDisplay_stats(int newDisplay_stats)
  {
    int oldDisplay_stats = display_stats;
    display_stats = newDisplay_stats;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.DISPLAY_STATS__DISPLAY_STATS, oldDisplay_stats, display_stats));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VideoGenPackage.DISPLAY_STATS__DISPLAY_STATS:
        return getDisplay_stats();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VideoGenPackage.DISPLAY_STATS__DISPLAY_STATS:
        setDisplay_stats((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VideoGenPackage.DISPLAY_STATS__DISPLAY_STATS:
        setDisplay_stats(DISPLAY_STATS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VideoGenPackage.DISPLAY_STATS__DISPLAY_STATS:
        return display_stats != DISPLAY_STATS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (display_stats: ");
    result.append(display_stats);
    result.append(')');
    return result.toString();
  }

} //Display_statsImpl
