/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.mlh.videoGen.VideoGenPackage;
import org.xtext.mlh.videoGen.VideoType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Video Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VideoTypeImpl extends MinimalEObjectImpl.Container implements VideoType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VideoTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoGenPackage.Literals.VIDEO_TYPE;
  }

} //VideoTypeImpl
