/**
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.videoGen.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.mlh.videoGen.Description;
import org.xtext.mlh.videoGen.Display_stats;
import org.xtext.mlh.videoGen.Duration;
import org.xtext.mlh.videoGen.VideoGenPackage;
import org.xtext.mlh.videoGen.VideoSeq;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Video Seq</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl#getVid <em>Vid</em>}</li>
 *   <li>{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl#getUrl <em>Url</em>}</li>
 *   <li>{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl#getDuration <em>Duration</em>}</li>
 *   <li>{@link org.xtext.mlh.videoGen.impl.VideoSeqImpl#getDisplay_stats <em>Display stats</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VideoSeqImpl extends MinimalEObjectImpl.Container implements VideoSeq
{
  /**
   * The default value of the '{@link #getVid() <em>Vid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVid()
   * @generated
   * @ordered
   */
  protected static final String VID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVid() <em>Vid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVid()
   * @generated
   * @ordered
   */
  protected String vid = VID_EDEFAULT;

  /**
   * The default value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected static final String URL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUrl() <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUrl()
   * @generated
   * @ordered
   */
  protected String url = URL_EDEFAULT;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected Description description;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected Duration duration;

  /**
   * The cached value of the '{@link #getDisplay_stats() <em>Display stats</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplay_stats()
   * @generated
   * @ordered
   */
  protected Display_stats display_stats;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VideoSeqImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoGenPackage.Literals.VIDEO_SEQ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVid()
  {
    return vid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVid(String newVid)
  {
    String oldVid = vid;
    vid = newVid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__VID, oldVid, vid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUrl()
  {
    return url;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUrl(String newUrl)
  {
    String oldUrl = url;
    url = newUrl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__URL, oldUrl, url));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Description getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDescription(Description newDescription, NotificationChain msgs)
  {
    Description oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DESCRIPTION, oldDescription, newDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescription(Description newDescription)
  {
    if (newDescription != description)
    {
      NotificationChain msgs = null;
      if (description != null)
        msgs = ((InternalEObject)description).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DESCRIPTION, null, msgs);
      if (newDescription != null)
        msgs = ((InternalEObject)newDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DESCRIPTION, null, msgs);
      msgs = basicSetDescription(newDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DESCRIPTION, newDescription, newDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Duration getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDuration(Duration newDuration, NotificationChain msgs)
  {
    Duration oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DURATION, oldDuration, newDuration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDuration(Duration newDuration)
  {
    if (newDuration != duration)
    {
      NotificationChain msgs = null;
      if (duration != null)
        msgs = ((InternalEObject)duration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DURATION, null, msgs);
      if (newDuration != null)
        msgs = ((InternalEObject)newDuration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DURATION, null, msgs);
      msgs = basicSetDuration(newDuration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DURATION, newDuration, newDuration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Display_stats getDisplay_stats()
  {
    return display_stats;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDisplay_stats(Display_stats newDisplay_stats, NotificationChain msgs)
  {
    Display_stats oldDisplay_stats = display_stats;
    display_stats = newDisplay_stats;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS, oldDisplay_stats, newDisplay_stats);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDisplay_stats(Display_stats newDisplay_stats)
  {
    if (newDisplay_stats != display_stats)
    {
      NotificationChain msgs = null;
      if (display_stats != null)
        msgs = ((InternalEObject)display_stats).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS, null, msgs);
      if (newDisplay_stats != null)
        msgs = ((InternalEObject)newDisplay_stats).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS, null, msgs);
      msgs = basicSetDisplay_stats(newDisplay_stats, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS, newDisplay_stats, newDisplay_stats));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VideoGenPackage.VIDEO_SEQ__DESCRIPTION:
        return basicSetDescription(null, msgs);
      case VideoGenPackage.VIDEO_SEQ__DURATION:
        return basicSetDuration(null, msgs);
      case VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS:
        return basicSetDisplay_stats(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VideoGenPackage.VIDEO_SEQ__VID:
        return getVid();
      case VideoGenPackage.VIDEO_SEQ__URL:
        return getUrl();
      case VideoGenPackage.VIDEO_SEQ__DESCRIPTION:
        return getDescription();
      case VideoGenPackage.VIDEO_SEQ__DURATION:
        return getDuration();
      case VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS:
        return getDisplay_stats();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VideoGenPackage.VIDEO_SEQ__VID:
        setVid((String)newValue);
        return;
      case VideoGenPackage.VIDEO_SEQ__URL:
        setUrl((String)newValue);
        return;
      case VideoGenPackage.VIDEO_SEQ__DESCRIPTION:
        setDescription((Description)newValue);
        return;
      case VideoGenPackage.VIDEO_SEQ__DURATION:
        setDuration((Duration)newValue);
        return;
      case VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS:
        setDisplay_stats((Display_stats)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VideoGenPackage.VIDEO_SEQ__VID:
        setVid(VID_EDEFAULT);
        return;
      case VideoGenPackage.VIDEO_SEQ__URL:
        setUrl(URL_EDEFAULT);
        return;
      case VideoGenPackage.VIDEO_SEQ__DESCRIPTION:
        setDescription((Description)null);
        return;
      case VideoGenPackage.VIDEO_SEQ__DURATION:
        setDuration((Duration)null);
        return;
      case VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS:
        setDisplay_stats((Display_stats)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VideoGenPackage.VIDEO_SEQ__VID:
        return VID_EDEFAULT == null ? vid != null : !VID_EDEFAULT.equals(vid);
      case VideoGenPackage.VIDEO_SEQ__URL:
        return URL_EDEFAULT == null ? url != null : !URL_EDEFAULT.equals(url);
      case VideoGenPackage.VIDEO_SEQ__DESCRIPTION:
        return description != null;
      case VideoGenPackage.VIDEO_SEQ__DURATION:
        return duration != null;
      case VideoGenPackage.VIDEO_SEQ__DISPLAY_STATS:
        return display_stats != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (vid: ");
    result.append(vid);
    result.append(", url: ");
    result.append(url);
    result.append(')');
    return result.toString();
  }

} //VideoSeqImpl
