/**
 * generated by Xtext 2.15.0
 */
package fr.istic.validation;

import fr.istic.validation.AbstractVideoGenValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VideoGenValidator extends AbstractVideoGenValidator {
}
