/**
 * generated by Xtext 2.15.0
 */
package fr.istic.ui;

import fr.istic.ui.AbstractVideoGenUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class VideoGenUiModule extends AbstractVideoGenUiModule {
  public VideoGenUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
