/*
 * generated by Xtext 2.15.0
 */
package org.xtext.mlh.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mlh.VideoGen.ui.internal.VideoGenActivator;

public class VideoGenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VideoGenActivator.getInstance().getInjector("org.xtext.mlh.VideoGen");
	}

}
